### ISSUE TITLE
PE definition in HcalRecHits needs to change

### ISSUE THREAD

**Issue by cmantill** [LDMX-Software/Hcal#16]
The definition of PEs in the double-sided readout channel changed from the sum of both channels to the average in the last big update of the digi code, as noted by @mrsolt :

- Before, the PE of one recHit was defined as the sum of PEs for both ends of a bar: https://github.com/LDMX-Software/Hcal/blob/c65ff2a64db639ede04c5eb76e0304301aa0af51/src/Hcal/HcalDigiProducer.cxx#L227-L235
- Now, the PE of one recHit is defined as the average, since the voltage is averaged for both ends of a bar: https://github.com/LDMX-Software/Hcal/blob/002f9608022a4cfd48776addb385188445c51105/src/Hcal/HcalRecProducer.cxx#L247-L248

This sets the number of PEs different by a factor of 2 which can affect the Veto for which the PE threshold remains unchanged.

**Comment by tomeichlersmith** [comment]
Resolved by PR #17
