### ISSUE TITLE
HCal veto input collection is not configurable 

### ISSUE THREAD

**Issue by bryngemark** [LDMX-Software/Hcal#18]
... neither is the pass name, nor the output collection name. 
See the Ecal veto for a good set of configurable parameters. 

This is a problem when we want to
1. run on a rerecoed collection, distinguished by a specific pass name 
2. run a new version of the Hcal veto under a new output collection name, on the same input
3. run the veto on collections with pileup overlay (which by design have to have a different name than the "sim event" collections)

**Comment by EinarElen** [comment]
Closed by #70
