### ISSUE TITLE
HCal Pedestal Table Producer

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/Hcal#33]
Write a small processor taking decoded digis and producing a table of pedestals.

**Comment by jmmans** [comment]
I've coded this up on the add_pedestal_producer branch, but I'd like to stow the "fire script" somewhere also.  There doesn't seem to be a standard location?

**Comment by tomeichlersmith** [comment]
_For future readers_: we've agreed to put fire config scripts in an `exampleConfigs` directory.

**Comment by tomeichlersmith** [comment]
Resolved with PR #36
