### ISSUE TITLE
Load conditions and verify reconstruction by ID. See issue 34.

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/Hcal#42]
I've been able to separate the conditions into their own tables (#34 ), but now that we've got a first draft of the Hcal pedestals merged into our conditions-data repository, I want to use this as an example of how to use the index file to avoid having to update the pedestal table file path depending on the run being studied.

Should involve simply defining the conditions base URL and then we can construct the index file path from the base URL, e.g.
```python
conditions_base_URL = os.environ['LDMX_BASE']+'/conditions-data/'
entriesURL = '${LDMX_CONDITIONS_BASEURL}/Hcal/testbeam04-22/pedestals/index-v1_0_0.csv'
```
or something, will need to check details...

**Comment by cmantill** [comment]
Not quite working yet.

If I try: 
```
adc_pedestal = SimpleCSVDoubleTableProvider("hcal_adc_pedestal",["PEDESTAL_ADC"])
adc_pedestal.validForever(pedestal_csv) 
```
it works just fine.

However, when I try: 
```
adc_pedestal = SimpleCSVDoubleTableProvider("hcal_adc_pedestal",["PEDESTAL_ADC"])
adc_pedestal.conditions_baseURL = f'{conditions_base_URL}/Hcal/testbeam04-2022/pedestals/pedestal_full/'
adc_pedestal.entriesURL = f'index_v1_0_0.csv'
```

It gives a segfault. Attaching output here. 
[cond_segfault.log](https://github.com/LDMX-Software/Hcal/files/8894064/cond_segfault.log)
