### ISSUE TITLE
Using TOT calibration

### ISSUE THREAD

**Issue by jmuse13** [LDMX-Software/Hcal#44]
To use the TOT calibration, define two functions:

`def tot_energy_high(x,a,b):
    return (x-b)*a`
`def tot_energy_low(x,a,b,c,d):
    return ((x-c)/a)**(1/b)+d`

The basic usage is:

**sum_tot** is the sum of TOT values over time ticks in the event
**tot_list** is a row in the calibration .csv file

`if(tot_list[10] == 1):
    use_sum_adc`
`if(tot_list[10] == 0):`
    `if(sum_tot<tot_list[0][7]):
        use_sum_adc`
    `if(sum_tot<tot_list[0][2] and sum_tot>=tot_list[0][7]):
           tot_energy = tot_energy_low(sum_tot, tot_list[0][5], tot_list[0][6] , tot_list[0][7] , tot_list[0][8])`
   ` if(sum_tot>=tot_list[0][2]):
            tot_energy = tot_energy_high(sum_tot, tot_list[0][3], tot_list[0][4])`

Where the calibration .csv file is located [here](https://github.com/LDMX-Software/conditions-data/blob/tot_calib/Hcal/testbeam04-2022/tot_calibration/calibrated_tot_calib20220426.csv)

**Comment by tomeichlersmith** [comment]
Cool, going to sketch out a processor to use these :+1:
