### ISSUE TITLE
Floating point values in integer conditions table 

### ISSUE THREAD

**Issue by EinarElen** [LDMX-Software/Hcal#66]
We have a minor bug in one of the hardcoded conditions. The `TrigPrimConditions` table expects integers but `TOT_GAIN` is currently set to 2.5.  This will, presumably, just get narrowed to 2. We could either just change it to be 2 or change the table to expect floating point numbers. 

See https://github.com/LDMX-Software/ldmx-sw/issues/1199 and https://github.com/LDMX-Software/ldmx-sw/pull/1198#issuecomment-1717288314 for some context 

@therwig what do you think is best?

**Comment by therwig** [comment]
Thanks for catching this. I defer to the hcal experts, but assuming floating point gain values are reasonable I'd suggest updating the type.

**Comment by EinarElen** [comment]
Seems reasonable to me.

**Comment by tomeichlersmith** [comment]
**Floating point gain values are _not_ reasonable for trigger primitives**.

I think the gain should be rounded to an integer for _trigger primitives_ in order to reflect the fact that _in the chip preparing the information for the trigger_ we do not plan to have floating point operations.

**Comment by EinarElen** [comment]
Then I suggest we do the rounding explicitly in the configuration

**Comment by EinarElen** [comment]
Closed by PR https://github.com/LDMX-Software/Hcal/pull/70
