### ISSUE TITLE
Fixes to Hcal digitization

### ISSUE THREAD

**Issue by cmantill** [LDMX-Software/Hcal#7]
Things to fix: 
- Fix handling of SimHits. The current digitization code assumes Ecal SimHit merging, where SimHits are merged into constituents that have same position (but different times, amplitudes). This is not true for Hcal, where we need to process the SimHits that belong to a same bar and then use the digitization code to obtain two digis.

- Fix time shift to get over TOA threshold. The [fixed correction to the time shift ](https://github.com/LDMX-Software/Hcal/blob/trunk/src/Hcal/HcalDigiProducer.cxx#L207) should be included in the pulse parameters. The timePeak parameter should be derived such that it aligns with a pulse that is generated along the beamline, at x=0,y=0.

- Include the shift of a light-speed particle into the simhit time: [L203](https://github.com/LDMX-Software/Hcal/blob/trunk/src/Hcal/HcalDigiProducer.cxx#L203). This should align the sampling clocks such that a speed-of-light particle along the beamline would produce pulses /at/ the sampling time for each plane

**Comment by jmmans** [comment]
A first pass of fixing the first item in the list is done. (Fix handling of SimHits)

I think the last item (simulating the photon timing) might be complex-enough to have its own issue.  Some of these are pretty urgent for other users, while the last item will take some time.
